language: node_js
node_js:
  - 10
  - 6
  - 4
branches:
  only:
    - master
    - /^v[0-9]/
script:
  - nyc npm test
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
deploy:
  provider: npm
  email: 'public@erikdesjardins.io'
  api_key:
    secure: f9t+hZRGNFOdRz+rF7wtOCbJYQvse9SGh0cIIEYDPJcxFYWSyfF/jAMl20LEp7xnnw1+M52u2xfgBvAFEu1eftzKCU1jvbwVieciXWEGJOzvnuvPkKtqPmaXBmhi0sKa/BC3cKTdhzzQeAPyZHXC1AlomkKq8/ixzX82FNej3mxn7sCiOPJcRS574xx9kUrXnWS5eUX6PywPsrYJDHaPtFQ37xbzoMyVgXtVYjSteMuiaf6ykFml7Vwopst+JncQScy0YPjGGU4Yucc5XO8rMe0bDXF79TFYhPH+OdDcUEVEfWgUSyDRKdEq5My+Y8jpZvFfClzDYiW9Hk8/ZWvHOobNLdnlyzimOa1q0pDGiwUKE2HFpdLjlf8ayLnn0ZOjBLUSayg1e7PkenjxPlz0nq56grgDPzz3q6T+LeLZYYcVYKPoFnhO1lCI38kl7cILVijXghq3Tt3ZrdDcmEPVQ/Nc7C0MkyrQD+ZXWAhO2pagVvO6KGdkX0/wNR2pgKSe1zgR+H6Ri0iG9xX091mpZHBAefe+Tey2Jc/J3BnnAmFH3B16eKmojm69soCgQ0AeG93BgaVj3eLZ1CSQOZIHhxtZwaM6AvrkDNzvUrkNn36qOt2btU+hzF3WDzQ0SXFumwSqN7noz7UYua8l0xkVz3epEUL6Qw8nrR12I1+3ffE=
  on:
    tags: true
    node: 10
